# Copyright (c) 2022 Seagate Technology LLC and/or its Affiliates

# This program is free software: you can redistribute it and/or modify it
# under the terms of the Apache-2.0 license as published by
# the Apache Software Foundation, either version 2.0 of the License,
# or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for the specific language governing permissions and
# limitations under the License.

# You should have received a copy of the Apache-2.0 license
# along with this program. If not, see <https://www.apache.org/licenses/LICENSE-2.0>.
# For any questions about this software or licensing, please email
# opensource@seagate.com

# Configuration for alex - https://github.com/get-alex/alex

name: Management-Controller inclusive words scan
on:
  # Trigger the workflow on pull request labeled as cla-signed
  # and synchronize for the main branch
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main
  # Trigger the workflow on demand
  workflow_dispatch:
jobs:
  # Let's start the alex to scan
  alex:
    name: Alex report
    #if: ${{ github.event.label.name == 'alex' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Enable the permissions"
        run: |
          sudo chown -R root:root $GITHUB_WORKSPACE
      - uses: seagate/action-alex@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: added
          reporter: github-pr-review
          fail_on_error: true
          level: warning
